platform :ios, '17.0'
install! 'cocoapods', :deterministic_uuids => true
project 'Danmaku.xcodeproj'

target 'Danmaku' do
  pod 'MobileVLCKit', '3.7.2'
  target 'DanmakuAppTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
