package app.danmaku.desktop

import app.danmaku.domain.LibraryQualityIssueSeverity
import app.danmaku.domain.LibraryQualityIssueType

internal enum class DesktopUiLanguage(
    val storageValue: String,
    val displayName: String,
) {
    ENGLISH(
        storageValue = "en",
        displayName = "English",
    ),
    ZH_TW(
        storageValue = "zh-TW",
        displayName = "繁體中文",
    );

    val strings: DesktopStrings
        get() = fallbackDesktopStrings(this)

    companion object {
        fun fromStorageValue(value: String?): DesktopUiLanguage =
            entries.firstOrNull { it.storageValue == value } ?: ENGLISH
    }
}

private fun fallbackDesktopStrings(language: DesktopUiLanguage): DesktopStrings =
    desktopStrings {
        when (language) {
            DesktopUiLanguage.ENGLISH -> {
                localPlaybackLibraryNotIndexedError = "Index a library before preparing local playback."
                localPlaybackMediaMappingMissingError = "This episode is missing its indexed file mapping. Rescan the library and try again."
                localPlaybackMediaFileMissingError = "The indexed media file is no longer available. Check the folder or rescan the library."
                localPlaybackNoDandanplayMatchError = "No dandanplay match was found for this episode yet."
                localPlaybackPrepareFailedError = "Could not prepare local playback. Check the file and try again."
                dandanplayLibraryNotIndexedSummary = "library is not indexed"
                dandanplayPrepareFailedSummary = "dandanplay preparation failed"
                libraryQualityNoLibraryText = "Index a library before reviewing quality issues."
                libraryQualityEmptyText = "No library quality issues found."
                libraryQualityTotalTitle = "Issues"
                libraryQualityReviewTitle = "Review"
                libraryQualityWarningTitle = "Warnings"
                libraryQualityTotalCaption = "Scanner findings"
                libraryQualityReviewCaption = "Needs attention"
                libraryQualityWarningCaption = "Check when convenient"
                libraryQualityIssueCountSummary = { count -> "$count quality issues" }
                libraryQualityOpenCountSummary = { count -> "$count open" }
                libraryQualityHandledCountSummary = { count -> "$count handled" }
                libraryQualityAffectedFilesLabel = { count -> "$count affected files" }
                libraryQualityEvidenceLabel = "Evidence"
                libraryQualityAllHandledText = "All current quality issues have been handled."
                libraryQualityShowHandledAction = "Show handled"
                libraryQualityHideHandledAction = "Hide handled"
                libraryQualityIgnoreAction = "Ignore"
                libraryQualityResolveAction = "Resolve"
                libraryQualityReopenAction = "Reopen"
                libraryQualityOpenInspectorAction = "Open in inspector"
                libraryQualitySplitSeriesGuidance =
                    "Files here match different anime; inspect the affected files before resolving."
                libraryQualityMergeSeriesGuidance =
                    "Different local titles match the same anime; inspect the affected files before resolving."
                libraryQualityActionsPlannedText = "Ignore and resolve actions will be added after issue persistence."
                libraryQualityIssueTypeLabels = mapOf(
                    LibraryQualityIssueType.FOLDER_FILE_EPISODE_MISMATCH to "Folder/file episode mismatch",
                    LibraryQualityIssueType.DUPLICATE_EPISODE_NUMBER to "Duplicate episode number",
                    LibraryQualityIssueType.EPISODE_VARIANT_GROUP to "Episode variant group",
                    LibraryQualityIssueType.MISSING_EPISODE_NUMBER to "Missing episode number",
                    LibraryQualityIssueType.UNPARSED_EPISODE_NUMBER to "Unparsed episode number",
                    LibraryQualityIssueType.UNMATCHED_SERIES to "Unmatched series",
                    LibraryQualityIssueType.METADATA_EPISODE_COUNT_MISMATCH to "Metadata episode-count mismatch",
                    LibraryQualityIssueType.SPLIT_SERIES_CANDIDATE to "Split series candidate",
                    LibraryQualityIssueType.MERGE_SERIES_CANDIDATE to "Merge series candidate",
                )
                libraryQualitySeverityLabels = mapOf(
                    LibraryQualityIssueSeverity.REVIEW to "Review",
                    LibraryQualityIssueSeverity.WARNING to "Warning",
                )
                libraryQualityDecisionStateLabels = mapOf(
                    DesktopLibraryQualityIssueDecisionState.IGNORED to "Ignored",
                    DesktopLibraryQualityIssueDecisionState.RESOLVED to "Resolved",
                )
                metadataMatchNoConfiguredProvidersError = "No metadata search provider is configured. Add MyAnimeList or Bangumi settings first."
                metadataMatchProviderSearchFailed = "Provider search failed. Check provider settings and try again."
                suggestMissingMappingsAction = "Suggest missing"
                suggestingMappingsAction = "Suggesting..."
                pairedLibraryServerRejectedError = "The paired library server rejected the request. Check the server URL and pairing code."
                pairedLibraryUnreachableError = "Could not reach the paired library server. Make sure the PC is online and on this network."
                remotePlaybackPrepareFailedError = "Could not prepare remote playback. Reload the paired catalog and try again."
                errorLabel = "Error"
            }
            DesktopUiLanguage.ZH_TW -> {
                localPlaybackLibraryNotIndexedError = "請先建立媒體庫索引，再準備本機播放。"
                localPlaybackMediaMappingMissingError = "此集缺少索引檔案對應。請重新掃描媒體庫後再試一次。"
                localPlaybackMediaFileMissingError = "索引中的媒體檔案已無法使用。請檢查資料夾或重新掃描媒體庫。"
                localPlaybackNoDandanplayMatchError = "目前找不到此集的 dandanplay 對應。"
                localPlaybackPrepareFailedError = "無法準備本機播放。請檢查檔案後再試一次。"
                dandanplayLibraryNotIndexedSummary = "媒體庫尚未建立索引"
                dandanplayPrepareFailedSummary = "dandanplay 準備失敗"
                libraryQualityNoLibraryText = "請先建立媒體庫索引，再檢查品質問題。"
                libraryQualityEmptyText = "未發現媒體庫品質問題。"
                libraryQualityTotalTitle = "問題"
                libraryQualityReviewTitle = "需檢查"
                libraryQualityWarningTitle = "警告"
                libraryQualityTotalCaption = "掃描結果"
                libraryQualityReviewCaption = "需要處理"
                libraryQualityWarningCaption = "有空時檢查"
                libraryQualityIssueCountSummary = { count -> "$count 個品質問題" }
                libraryQualityOpenCountSummary = { count -> "$count 個未處理" }
                libraryQualityHandledCountSummary = { count -> "$count 個已處理" }
                libraryQualityAffectedFilesLabel = { count -> "$count 個受影響檔案" }
                libraryQualityEvidenceLabel = "證據"
                libraryQualityAllHandledText = "目前的媒體庫品質問題都已處理。"
                libraryQualityShowHandledAction = "顯示已處理"
                libraryQualityHideHandledAction = "隱藏已處理"
                libraryQualityIgnoreAction = "忽略"
                libraryQualityResolveAction = "解決"
                libraryQualityReopenAction = "重新開啟"
                libraryQualityOpenInspectorAction = "在檢視器開啟"
                libraryQualitySplitSeriesGuidance =
                    "這些檔案對應到不同動畫；解決前請檢查受影響檔案。"
                libraryQualityMergeSeriesGuidance =
                    "不同本機標題對應到同一動畫；解決前請檢查受影響檔案。"
                libraryQualityActionsPlannedText = "忽略與解決動作會在問題持久化後加入。"
                libraryQualityIssueTypeLabels = mapOf(
                    LibraryQualityIssueType.FOLDER_FILE_EPISODE_MISMATCH to "資料夾/檔名集數不一致",
                    LibraryQualityIssueType.DUPLICATE_EPISODE_NUMBER to "重複集數",
                    LibraryQualityIssueType.EPISODE_VARIANT_GROUP to "集數版本群組",
                    LibraryQualityIssueType.MISSING_EPISODE_NUMBER to "缺少集數",
                    LibraryQualityIssueType.UNPARSED_EPISODE_NUMBER to "無法解析集數",
                    LibraryQualityIssueType.UNMATCHED_SERIES to "未對應系列",
                    LibraryQualityIssueType.METADATA_EPISODE_COUNT_MISMATCH to "中繼資料集數不一致",
                    LibraryQualityIssueType.SPLIT_SERIES_CANDIDATE to "可能需要拆分系列",
                    LibraryQualityIssueType.MERGE_SERIES_CANDIDATE to "可能需要合併系列",
                )
                libraryQualitySeverityLabels = mapOf(
                    LibraryQualityIssueSeverity.REVIEW to "需檢查",
                    LibraryQualityIssueSeverity.WARNING to "警告",
                )
                libraryQualityDecisionStateLabels = mapOf(
                    DesktopLibraryQualityIssueDecisionState.IGNORED to "已忽略",
                    DesktopLibraryQualityIssueDecisionState.RESOLVED to "已解決",
                )
                metadataMatchNoConfiguredProvidersError = "尚未設定中繼資料搜尋服務。請先新增 MyAnimeList 或 Bangumi 設定。"
                metadataMatchProviderSearchFailed = "服務搜尋失敗。請檢查服務設定後再試一次。"
                suggestMissingMappingsAction = "建議缺少對應"
                suggestingMappingsAction = "建議中..."
                pairedLibraryServerRejectedError = "配對媒體庫伺服器拒絕請求。請檢查伺服器 URL 與配對碼。"
                pairedLibraryUnreachableError = "無法連線到配對媒體庫伺服器。請確認 PC 已開機且位於同一網路。"
                remotePlaybackPrepareFailedError = "無法準備遠端播放。請重新載入配對目錄後再試一次。"
                errorLabel = "錯誤"
            }
        }
    }

internal fun desktopStrings(configure: DesktopStrings.() -> Unit): DesktopStrings =
    DesktopStrings().apply(configure)

internal class DesktopStrings {
    var tabTitles: Map<DesktopShellTab, String> = emptyMap()
    var settingsSectionTitles: Map<DesktopSettingsSection, String> = emptyMap()
    var mediaHub: String = ""
    var shellSubtitle: String = ""
    var searchLabel: String = ""
    var playerStatusPrefix: String = ""
    var playerIdleStatusLabel: String = ""
    var playerPausedStatusLabel: String = ""
    var playerEndedStatusLabel: String = ""
    var playerErrorStatusLabel: String = ""
    var episodesSuffix: String = ""
    var rescanLibrary: String = ""
    var settingsTitle: String = ""
    var settingsDescription: String = ""
    var languageTitle: String = ""
    var languageDescription: String = ""
    var uiLanguageLabel: String = ""
    var uiLanguagesValue: String = ""
    var appLabel: String = ""
    var primaryTargetsLabel: String = ""
    var supportedLabel: String = ""
    var librarySettingsDescription: String = ""
    var metadataLabel: String = ""
    var metadataRefreshLibraryDetailsText: String = ""
    var importsLabel: String = ""
    var aniRssImportsManagedDownloadsText: String = ""
    var playbackRuntimeTitle: String = ""
    var mpvExecutorLabel: String = ""
    var rendererLabel: String = ""
    var mpvRendererDescription: String = ""
    var focusModeLabel: String = ""
    var playerFocusModeDescription: String = ""
    var storageCleanupDescription: String = ""
    var appLogLabel: String = ""
    var mpvLogLabel: String = ""
    var privacyCredentialsTitle: String = ""
    var privacyCredentialsDescription: String = ""
    var desktopRuntimeTitle: String = ""
    var privacyTitle: String = ""
    var credentialsPrivacyText: String = ""
    var playbackNeedsAttentionTitle: String = ""
    var preparingPlaybackTitle: String = ""
    var noMediaLoadedLabel: String = ""
    var playingLabel: String = ""
    var videoHostLabel: String = ""
    var openMediaFileAction: String = ""
    var chooseMediaFileTitle: (String) -> String = { _ -> "" }
    var chooseAnimeLibraryFolderTitle: String = ""
    var chooseAniRssCompletedMediaFolderTitle: String = ""
    var homeAction: String = ""
    var libraryAction: String = ""
    var showPlayerChromeAction: String = ""
    var hidePlayerChromeAction: String = ""
    var previousEpisodeAction: String = ""
    var previousEpisodeWithTitle: (String) -> String = { _ -> "" }
    var nextEpisodeAction: String = ""
    var nextEpisodeWithTitle: (String) -> String = { _ -> "" }
    var backThirtySecondsAction: String = ""
    var backTenSecondsAction: String = ""
    var playAction: String = ""
    var watchSummaryProgressLabel: (Int, Int, Int) -> String = { _, _, _ -> "" }
    var forwardTenSecondsAction: String = ""
    var forwardThirtySecondsAction: String = ""
    var volumeLabel: String = ""
    var subtitleShortLabel: String = ""
    var hideDanmakuPanelAction: String = ""
    var showDanmakuPanelAction: String = ""
    var exitFullscreenAction: String = ""
    var enterFullscreenAction: String = ""
    var libraryStepLabel: String = ""
    var preparingMediaStepText: String = ""
    var playerRuntimeStepLabel: String = ""
    var libraryPreparationStepLabel: String = ""
    var danmakuTitle: String = ""
    var shownLabel: String = ""
    var hiddenLabel: String = ""
    var cacheLabel: String = ""
    var audioLabel: String = ""
    var subtitleLabel: String = ""
    var defaultLabel: String = ""
    var offLabel: String = ""
    var hideAction: String = ""
    var showAction: String = ""
    var opacityLabel: String = ""
    var densityLabel: String = ""
    var fontLabel: String = ""
    var speedLabel: String = ""
    var areaLabel: String = ""
    var offsetLabel: String = ""
    var librarySlicesTitle: String = ""
    var animeSeriesSliceLabel: String = ""
    var moviesSliceLabel: String = ""
    var ovasSpecialsSliceLabel: String = ""
    var allEpisodesSliceLabel: String = ""
    var favoritesSliceLabel: String = ""
    var nowPlayingTitle: String = ""
    var recentlyAddedTitle: String = ""
    var browseAllAction: String = ""
    var newlyAddedEmptyText: String = ""
    var recentlyAddedDetailLabel: (Long, String) -> String = { _, _ -> "" }
    var recentlyWatchedTitle: String = ""
    var recentPlaybackEmptyText: String = ""
    var watchedAtLabel: (Long) -> String = { _ -> "" }
    var myLibraryTitle: String = ""
    var seriesSummaryTitle: String = ""
    var matchedGroupsCaption: String = ""
    var favoritesSummaryTitle: String = ""
    var savedEpisodesCaption: String = ""
    var watchingSummaryTitle: String = ""
    var inProgressCaption: String = ""
    var homeLibraryEmptyText: String = ""
    var librarySnapshotTitle: String = ""
    var continueWatchingTitle: String = ""
    var noResumeQueueText: String = ""
    var loadedNowLabel: String = ""
    var localPlaybackLibraryNotIndexedError: String = ""
    var localPlaybackMediaMappingMissingError: String = ""
    var localPlaybackMediaFileMissingError: String = ""
    var localPlaybackNoDandanplayMatchError: String = ""
    var localPlaybackPrepareFailedError: String = ""
    var dandanplayLibraryNotIndexedSummary: String = ""
    var dandanplayPrepareFailedSummary: String = ""
    var resumeAtLabel: (Long) -> String = { _ -> "" }
    var resumeSavedPositionLabel: String = ""
    var savedPositionLabel: String = ""
    var lastWatchedLabel: String = ""
    var nextAfterLabel: (Long?) -> String = { _ -> "" }
    var startWatchingLibraryLabel: String = ""
    var episodeCountShortLabel: (Int) -> String = { _ -> "" }
    var libraryViewTitles: Map<WindowsLibraryView, String> = emptyMap()
    var libraryHostSubtitle: String = ""
    var librarySearchLabel: String = ""
    var libraryToolbarCompactDescription: String = ""
    var libraryToolbarDescription: String = ""
    var episodeCountSummary: (Int, Int) -> String = { _, _ -> "" }
    var favoriteCountSummary: (Int) -> String = { _ -> "" }
    var localWatchListCountSummary: (Int) -> String = { _ -> "" }
    var favoriteEpisodesFilterEmptyText: String = ""
    var episodesFilterEmptyText: String = ""
    var noIndexedSeriesText: String = ""
    var noSeriesFilterMatchesText: String = ""
    var noInProgressLocalEpisodesText: String = ""
    var noNextUpItemText: String = ""
    var noRecentlyWatchedLocalEpisodesText: String = ""
    var subtitlesOnlyLabel: String = ""
    var pathSortLabel: String = ""
    var requireSubtitlesAction: String = ""
    var showAllSubtitlesAction: String = ""
    var favoritesOnlyAction: String = ""
    var showAllFavoritesAction: String = ""
    var anyWatchListStatusAction: String = ""
    var untrackedWatchListStatusAction: String = ""
    var sortByPathAction: String = ""
    var sortByTitleAction: String = ""
    var openLibraryImportPanelAction: String = ""
    var rescanFoldersAction: String = ""
    var localPcLabel: String = ""
    var indexingLabel: String = ""
    var externalListsLabel: String = ""
    var noLibraryLabel: String = ""
    var pairedDevicesLabel: String = ""
    var lanBrowserReadyLabel: String = ""
    var foldersLabel: String = ""
    var noFoldersLabel: String = ""
    var moreItemsLabel: (Int) -> String = { _ -> "" }
    var lastScanSummary: (Int, Int) -> String = { _, _ -> "" }
    var lastScanCountsSummary: (Int, Int) -> String = { _, _ -> "" }
    var libraryQualityNoLibraryText: String = ""
    var libraryQualityEmptyText: String = ""
    var libraryQualityIssueCountSummary: (Int) -> String = { _ -> "" }
    var libraryQualityOpenCountSummary: (Int) -> String = { _ -> "" }
    var libraryQualityHandledCountSummary: (Int) -> String = { _ -> "" }
    var libraryQualityTotalTitle: String = ""
    var libraryQualityReviewTitle: String = ""
    var libraryQualityWarningTitle: String = ""
    var libraryQualityTotalCaption: String = ""
    var libraryQualityReviewCaption: String = ""
    var libraryQualityWarningCaption: String = ""
    var libraryQualityAffectedFilesLabel: (Int) -> String = { _ -> "" }
    var libraryQualityEvidenceLabel: String = ""
    var libraryQualityAllHandledText: String = ""
    var libraryQualityShowHandledAction: String = ""
    var libraryQualityHideHandledAction: String = ""
    var libraryQualityIgnoreAction: String = ""
    var libraryQualityResolveAction: String = ""
    var libraryQualityReopenAction: String = ""
    var libraryQualityOpenInspectorAction: String = ""
    var libraryQualitySplitSeriesGuidance: String = ""
    var libraryQualityMergeSeriesGuidance: String = ""
    var libraryQualityActionsPlannedText: String = ""
    var libraryQualityIssueTypeLabels: Map<LibraryQualityIssueType, String> = emptyMap()
    var libraryQualitySeverityLabels: Map<LibraryQualityIssueSeverity, String> = emptyMap()
    var libraryQualityDecisionStateLabels: Map<DesktopLibraryQualityIssueDecisionState, String> = emptyMap()
    var libraryImportTitle: String = ""
    var aniRssRootCountLabel: (Int) -> String = { _ -> "" }
    var scanRunningLabel: String = ""
    var publishedLabel: String = ""
    var lastScanTitle: String = ""
    var reusedCountLabel: (Int) -> String = { _ -> "" }
    var notRunLabel: String = ""
    var addFolderAction: String = ""
    var importAniRssOutputAction: String = ""
    var rescanAllAction: String = ""
    var rescanAction: String = ""
    var scanningAction: String = ""
    var indexingLibraryRootsLabel: String = ""
    var registeredRootsTitle: String = ""
    var libraryImportEmptyText: String = ""
    var removeLibraryFolderTitle: String = ""
    var removeLibraryFolderText: (String) -> String = { _ -> "" }
    var removeFolderAction: String = ""
    var userSelectedFolderLabel: String = ""
    var aniRssOutputFolderLabel: String = ""
    var libraryRootAvailableLabel: String = ""
    var libraryRootMissingLabel: String = ""
    var lastScannedAtLabel: (Long) -> String = { _ -> "" }
    var notScannedYetLabel: String = ""
    var inspectorResizeHandleLabel: String = ""
    var resetInspectorWidthAction: String = ""
    var inspectorTitle: String = ""
    var inspectorEmptyText: String = ""
    var nextPlayableLabel: (String) -> String = { _ -> "" }
    var loadingAction: String = ""
    var preparingAction: String = ""
    var prepareAction: String = ""
    var prepareShortAction: String = ""
    var detailsAction: String = ""
    var favoriteAction: String = ""
    var unfavoriteAction: String = ""
    var showEpisodeDetailsAction: String = ""
    var checkCachedDanmakuAction: String = ""
    var moreEpisodeActionsAction: String = ""
    var externalIdsTitle: String = ""
    var matchAction: String = ""
    var linkAction: String = ""
    var replaceAction: String = ""
    var correctAction: String = ""
    var providerEpisodeLabel: (String) -> String = { _ -> "" }
    var preparePlaybackAction: String = ""
    var refreshEpisodeMetadataAction: String = ""
    var refreshingEpisodeMetadataAction: String = ""
    var refreshSeriesMetadataAction: String = ""
    var refreshingSeriesMetadataAction: String = ""
    var loadIntoPlayerAction: String = ""
    var refreshDanmakuAction: String = ""
    var attachLocalDanmakuAction: String = ""
    var attachLocalDanmakuShortAction: String = ""
    var removeOverlayAction: String = ""
    var clearDanmakuCacheAction: String = ""
    var clearCacheAction: String = ""
    var enableAutoNextAction: String = ""
    var disableAutoNextAction: String = ""
    var autoNextOnLabel: String = ""
    var autoNextOffLabel: String = ""
    var readinessTitle: String = ""
    var preparedPlaybackLabel: String = ""
    var prepareToInspectTracksLabel: String = ""
    var notPreparedLabel: String = ""
    var resumeValueLabel: (Long) -> String = { _ -> "" }
    var notCheckedYetLabel: String = ""
    var subtitlesIndexedLabel: (Int) -> String = { _ -> "" }
    var episodesTitle: String = ""
    var advancedTitle: String = ""
    var favoriteStatusLabel: String = ""
    var pairedLibraryTitle: String = ""
    var pairedLibraryDescription: String = ""
    var pairedLibraryServerUrlLabel: String = ""
    var pairingCodeLabel: String = ""
    var loadPairedCatalogAction: String = ""
    var pairedLibraryErrorLabel: (String) -> String = { _ -> "" }
    var pairedLibraryServerRejectedError: String = ""
    var pairedLibraryUnreachableError: String = ""
    var remotePlaybackPrepareFailedError: String = ""
    var pairedEpisodesLabel: (Int) -> String = { _ -> "" }
    var pairedProgressLabel: String = ""
    var savedRowsLabel: (Int) -> String = { _ -> "" }
    var pairedNextUpTitle: String = ""
    var pairedNextUpEmptyText: String = ""
    var pairedContinueWatchingTitle: String = ""
    var pairedContinueWatchingEmptyText: String = ""
    var searchPairedEpisodesLabel: String = ""
    var sortTitleAction: String = ""
    var sortPathAction: String = ""
    var showingLabel: String = ""
    var pairedEpisodesCountLabel: (Int, Int) -> String = { _, _ -> "" }
    var pairedCatalogEmptyText: String = ""
    var pairedServerEmptyText: String = ""
    var pairedFilterEmptyText: String = ""
    var resetFiltersAction: String = ""
    var preparedDesktopPlaybackLabel: (String, String) -> String = { _, _ -> "" }
    var sourceValueLabel: (String) -> String = { _ -> "" }
    var resumeValueText: (String) -> String = { _ -> "" }
    var startFromBeginningLabel: String = ""
    var loadIntoDesktopControllerAction: String = ""
    var unknownMediaLabel: String = ""
    var unknownDurationLabel: String = ""
    var noSubtitlesLabel: String = ""
    var subtitleCountLabel: (Int) -> String = { _ -> "" }
    var downloadFilterTitles: Map<DownloadQueueFilter, String> = emptyMap()
    var downloadsActiveTitle: String = ""
    var downloadsActiveCaption: String = ""
    var downloadsQueuedTitle: String = ""
    var downloadsQueuedCaption: String = ""
    var downloadsCompletedTitle: String = ""
    var downloadsCompletedCaption: String = ""
    var downloadsFailedTitle: String = ""
    var downloadsFailedCaption: String = ""
    var downloadQueueTitle: String = ""
    var refreshDownloadQueueAction: String = ""
    var downloadQueuePolicyText: String = ""
    var downloadQueueEmptyText: String = ""
    var downloadQueueFilterEmptyText: (String) -> String = { _ -> "" }
    var openOutputFolderAction: String = ""
    var removeQueueItemAction: String = ""
    var removeDownloadTitle: String = ""
    var removeDownloadText: (String) -> String = { _ -> "" }
    var removeAction: String = ""
    var downloadSetupAuthorizedSourcesTitle: String = ""
    var downloadSetupAuthorizedSourcesText: String = ""
    var authorizedImportsOnlyLabel: String = ""
    var queueExecutionPlannedLabel: String = ""
    var importRootCountLabel: (Int) -> String = { _ -> "" }
    var addAniRssOutputFolderAction: String = ""
    var aniRssWebhookTitle: String = ""
    var noWebhookUrlText: String = ""
    var webhookUrlLabel: String = ""
    var webhookHeaderLabel: String = ""
    var webhookTokenLabel: String = ""
    var importRootsTitle: String = ""
    var noAniRssRootsText: String = ""
    var downloadInspectorTitle: String = ""
    var downloadInspectorEmptyText: String = ""
    var stateLabel: String = ""
    var progressLabel: String = ""
    var createdLabel: String = ""
    var updatedLabel: String = ""
    var outputLabel: String = ""
    var sourceLabel: String = ""
    var failureLabel: String = ""
    var openFolderAction: String = ""
    var pauseAction: String = ""
    var resumeAction: String = ""
    var retryAction: String = ""
    var cancelAction: String = ""
    var downloadExecutionPlannedText: String = ""
    var dandanplayProvidersTitle: String = ""
    var dandanplayProvidersDescription: String = ""
    var cacheExpiryLabel: String = ""
    var lastTestLabel: String = ""
    var apiBaseUrlLabel: String = ""
    var appIdOptionalLabel: String = ""
    var appSecretKeepLabel: String = ""
    var appSecretOptionalLabel: String = ""
    var cacheMaxAgeDaysLabel: String = ""
    var signedAuthAction: String = ""
    var credentialAuthAction: String = ""
    var currentAuthLabel: (String) -> String = { _ -> "" }
    var saveDandanplaySettingsAction: String = ""
    var testSavedAction: String = ""
    var clearAction: String = ""
    var cleanExpiredCacheAction: String = ""
    var clearDandanplayTitle: String = ""
    var clearDandanplayText: String = ""
    var cleanExpiredDandanplayTitle: String = ""
    var cleanExpiredDandanplayText: String = ""
    var externalAnimeListsTitle: String = ""
    var externalAnimeListsDescription: String = ""
    var myAnimeListTestLabel: String = ""
    var bangumiTestLabel: String = ""
    var myAnimeListClientIdLabel: String = ""
    var myAnimeListAccessTokenKeepLabel: String = ""
    var myAnimeListAccessTokenOptionalLabel: String = ""
    var myAnimeListClientSecretKeepLabel: String = ""
    var myAnimeListClientSecretOptionalLabel: String = ""
    var bangumiApiBaseUrlLabel: String = ""
    var bangumiUserAgentLabel: String = ""
    var bangumiUserAgentRequiredError: String = ""
    var bangumiAccessTokenKeepLabel: String = ""
    var bangumiAccessTokenOptionalLabel: String = ""
    var saveExternalListsAction: String = ""
    var connectMyAnimeListAction: String = ""
    var testMyAnimeListAction: String = ""
    var testBangumiAction: String = ""
    var clearMyAnimeListAction: String = ""
    var clearBangumiAction: String = ""
    var clearMyAnimeListTitle: String = ""
    var clearMyAnimeListText: String = ""
    var clearBangumiTitle: String = ""
    var clearBangumiText: String = ""
    var localServerTitle: String = ""
    var serverBaseUrlLabel: String = ""
    var lanUrlLabel: String = ""
    var lanUrlsLabel: String = ""
    var lanUrlNumberedLabel: (Int) -> String = { _ -> "" }
    var discoveryLabel: String = ""
    var openServerDashboardAction: String = ""
    var testLocalServerAction: String = ""
    var serverDashboardTitle: String = ""
    var pairingAndLanAccessTitle: String = ""
    var healthTitle: String = ""
    var notCheckedThisSessionLabel: String = ""
    var recentRequestsLabel: String = ""
    var connectedClientsLabel: String = ""
    var connectedClientsPlannedText: String = ""
    var bandwidthLabel: String = ""
    var bandwidthPlannedText: String = ""
    var recentServerRequestsTitle: String = ""
    var noServerRequestsText: String = ""
    var testServerAction: String = ""
    var copyAction: String = ""
    var testingStatusLabel: String = ""
    var okStatusLabel: String = ""
    var failedStatusLabel: String = ""
    var homeServerStatusTitle: String = ""
    var attentionNeededLabel: String = ""
    var onlineLabel: String = ""
    var noLanUrlDetectedLabel: String = ""
    var pairingLabel: String = ""
    var episodesLabel: String = ""
    var errorLabel: String = ""
    var metadataAndPostersTitle: String = ""
    var loadingLabel: String = ""
    var partialLabel: String = ""
    var waitingLabel: String = ""
    var metadataLoadingLabel: String = ""
    var metadataFailedLabel: String = ""
    var metadataReadyLabel: String = ""
    var metadataPartialLabel: String = ""
    var metadataNeededLabel: String = ""
    var metadataFailedShortLabel: String = ""
    var metadataReadyShortLabel: String = ""
    var metadataNeededShortLabel: String = ""
    var metadataLoadingDetail: String = ""
    var metadataFailedDetail: String = ""
    var metadataReadyDetail: String = ""
    var metadataPartialMatchedNoPosterDetail: String = ""
    var metadataPartialPosterNoTitleDetail: String = ""
    var metadataPartialGenericDetail: String = ""
    var metadataNeededDetail: String = ""
    var seriesMetadataLoadingDetail: String = ""
    var seriesMetadataFailedDetail: String = ""
    var seriesMetadataReadyDetail: String = ""
    var seriesMetadataPartialDetail: String = ""
    var seriesMetadataNeededDetail: String = ""
    var fileGroupLabel: (String) -> String = { _ -> "" }
    var postersReadySummary: (Int, Int) -> String = { _, _ -> "" }
    var refreshAction: String = ""
    var refreshingAction: String = ""
    var lastScanLabel: String = ""
    var groupsLabel: String = ""
    var externalSyncTitle: String = ""
    var notMappedLabel: String = ""
    var readyUpdatesLabel: (Int) -> String = { _ -> "" }
    var openTrackingAction: String = ""
    var downloadQueueReadyLabel: String = ""
    var downloadsImportDetail: String = ""
    var openDownloadsAction: String = ""
    var cachedDanmakuTitle: String = ""
    var notCheckedLabel: String = ""
    var manageCacheAction: String = ""
    var danmakuCacheSettingsTitle: String = ""
    var danmakuCacheSettingsDescription: String = ""
    var cachedEpisodesLabel: String = ""
    var openCacheManagerAction: String = ""
    var danmakuCacheManagerTitle: String = ""
    var cachedSummaryTitle: String = ""
    var expiredSummaryTitle: String = ""
    var commentsSummaryTitle: String = ""
    var cachedEventsCaption: String = ""
    var cacheDayRuleCaption: (Int) -> String = { _ -> "" }
    var persistedEntriesTitle: String = ""
    var noDandanplayCachesText: String = ""
    var selectedCacheTitle: String = ""
    var selectCachePromptText: String = ""
    var expiredStatusLabel: String = ""
    var cacheEntryCommentSummary: (Int, Long, String) -> String = { _, _, _ -> "" }
    var animeLabel: String = ""
    var episodeLabel: String = ""
    var mediaIdLabel: String = ""
    var fileLabel: String = ""
    var fileSizeLabel: String = ""
    var commentsLabel: String = ""
    var fetchedLabel: String = ""
    var shiftLabel: String = ""
    var unknownAnimeLabel: String = ""
    var unknownEpisodeLabel: String = ""
    var noneLabel: String = ""
    var shiftSecondsLabel: (Double) -> String = { _ -> "" }
    var assCacheLabel: String = ""
    var deleteCachedDanmakuTitle: String = ""
    var deleteCachedDanmakuText: (String) -> String = { _ -> "" }
    var deleteCacheAction: String = ""
    var cleanExpiredDanmakuCachesTitle: String = ""
    var cleanExpiredDanmakuCachesText: (Int) -> String = { _ -> "" }
    var cleanExpiredAction: String = ""
    var providerSettingsAction: String = ""
    var myAnimeListClientSavedLabel: String = ""
    var trackingCredentialsNeededLabel: String = ""
    var providerNotConfiguredStatus: String = ""
    var myAnimeListOauthTokenSavedStatus: String = ""
    var myAnimeListClientIdSecretSavedStatus: String = ""
    var myAnimeListClientIdSearchSavedStatus: String = ""
    var bangumiAccessTokenSavedStatus: String = ""
    var bangumiPublicSearchOnlyStatus: String = ""
    var dandanplayConfiguredStatus: (String, String) -> String = { _, _ -> "" }
    var dandanplayCompatibleApiStatus: String = ""
    var dandanplayNotConfiguredStatus: String = ""
    var externalSyncSummaryLabel: (Int, Int, Int) -> String = { _, _, _ -> "" }
    var externalProgressAheadReason: String = ""
    var externalListWatchingStatus: String = ""
    var externalListCompletedStatus: String = ""
    var externalListOnHoldStatus: String = ""
    var externalListDroppedStatus: String = ""
    var externalListPlanToWatchStatus: String = ""
    var externalListUnchangedStatus: String = ""
    var watchedEpisodeProgressLabel: (Int, Int) -> String = { _, _ -> "" }
    var mappedSummaryTitle: String = ""
    var mappedSummaryCaption: String = ""
    var readySummaryTitle: String = ""
    var readySummaryCaption: String = ""
    var conflictsSummaryTitle: String = ""
    var conflictsSummaryCaption: String = ""
    var failuresSummaryTitle: String = ""
    var failuresSummaryCaption: String = ""
    var trackingSyncPreviewTitle: String = ""
    var openLibraryAction: String = ""
    var noExternalSyncLibraryText: String = ""
    var providerUpdatesCaption: String = ""
    var externalAheadCaption: String = ""
    var mappingChecksCaption: String = ""
    var syncingUpdatesAction: String = ""
    var syncReadyUpdatesAction: String = ""
    var noProviderWritesReadyText: String = ""
    var writesReadyUpdatesText: (Int) -> String = { _ -> "" }
    var dryRunUpdatesTitle: String = ""
    var noExternalProgressUpdatesText: String = ""
    var noExternalProgressConflictsText: String = ""
    var syncFailuresTitle: String = ""
    var noSyncFailuresText: String = ""
    var moreSkippedLabel: (Int) -> String = { _ -> "" }
    var localWatchedEpisodesLabel: (Int) -> String = { _ -> "" }
    var externalWatchedEpisodesLabel: (Int) -> String = { _ -> "" }
    var syncAttemptLabel: (Int) -> String = { _ -> "" }
    var trackingNoLibraryText: String = ""
    var trackingTableTitle: String = ""
    var trackingTableDescription: String = ""
    var syncAllReadyAction: String = ""
    var syncingAction: String = ""
    var trackingRowsEmptyText: String = ""
    var localSeriesHeader: String = ""
    var providerHeader: String = ""
    var actionHeader: String = ""
    var mappingInspectorTitle: String = ""
    var mappingInspectorEmptyText: String = ""
    var animeIdLabel: String = ""
    var providerUrlLabel: String = ""
    var localSeriesIdLabel: String = ""
    var localProgressLabel: String = ""
    var providerProgressLabel: String = ""
    var providerListStatusLabel: String = ""
    var providerScoreLabel: String = ""
    var localWatchListTitle: String = ""
    var localScoreLabel: String = ""
    var localNotesLabel: String = ""
    var saveLocalWatchListAction: String = ""
    var clearLocalWatchListAction: String = ""
    var confidenceLabel: String = ""
    var statusLabel: String = ""
    var conflictLabel: String = ""
    var externalWatchedLabel: String = ""
    var nextRetryLabel: String = ""
    var skippedLabel: String = ""
    var syncSelectedAction: String = ""
    var refreshProviderStateAction: String = ""
    var removeMappingAction: String = ""
    var resolveConflictAction: String = ""
    var trackingPlannedControlsText: String = ""
    var readbackPendingLabel: String = ""
    var readyStatusLabel: String = ""
    var reviewConflictAction: String = ""
    var conflictStatusLabel: String = ""
    var externalProviderLabel: String = ""
    var notLinkedLabel: String = ""
    var noLinkLabel: String = ""
    var missingLocalSeriesReason: String = ""
    var unmappedLocalSeriesReason: String = ""
    var needsMappingLabel: String = ""
    var missingLocalSeriesLabel: String = ""
    var retryAtLabel: (Long) -> String = { _ -> "" }
    var failedAttemptsLabel: (Int) -> String = { _ -> "" }
    var watchedCountLabel: (Int) -> String = { _ -> "" }
    var searchAction: String = ""
    var searchingAction: String = ""
    var closeAction: String = ""
    var useAction: String = ""
    var mappedAction: String = ""
    var posterLoadingLabel: String = ""
    var posterUnavailableLabel: String = ""
    var danmakuDisplaySettingsTitle: String = ""
    var danmakuDisplaySettingsDescription: String = ""
    var visibilityLabel: String = ""
    var fontScaleLabel: String = ""
    var displayAreaLabel: String = ""
    var showDanmakuAction: String = ""
    var hideDanmakuAction: String = ""
    var opacityPercentLabel: String = ""
    var fontScalePercentLabel: String = ""
    var speedPercentLabel: String = ""
    var densityPercentLabel: String = ""
    var displayAreaPercentLabel: String = ""
    var offsetMsLabel: String = ""
    var keywordFiltersLabel: String = ""
    var regexFiltersLabel: String = ""
    var offsetMsValueLabel: (Long) -> String = { _ -> "" }
    var saveDanmakuDisplayAction: String = ""
    var resetDraftAction: String = ""
    var diagnosticsTitle: String = ""
    var noDiagnosticsText: String = ""
    var metadataMatchTitle: String = ""
    var metadataMatchDescription: (String) -> String = { _ -> "" }
    var metadataMatchSearchTitleLabel: String = ""
    var metadataMatchSelectProviderError: String = ""
    var metadataMatchNoConfiguredProvidersError: String = ""
    var metadataMatchProviderSearchFailed: String = ""
    var metadataMatchNoCandidates: (String) -> String = { _ -> "" }
    var metadataMatchMyAnimeListUnavailable: String = ""
    var metadataMatchBangumiUnavailable: String = ""
    var metadataMatchCurrentMappingsPrefix: String = ""
    var metadataMatchEmptyState: String = ""
    var metadataMatchMatchedTitlePrefix: String = ""
    var suggestMissingMappingsAction: String = ""
    var suggestingMappingsAction: String = ""
    fun tabTitle(tab: DesktopShellTab): String = tabTitles[tab] ?: tab.title
    fun settingsSectionTitle(section: DesktopSettingsSection): String =
        settingsSectionTitles[section] ?: section.title
    fun libraryViewTitle(view: WindowsLibraryView): String = libraryViewTitles[view] ?: view.label
    fun libraryQualityIssueTypeLabel(type: LibraryQualityIssueType): String =
        libraryQualityIssueTypeLabels[type] ?: type.name
    fun libraryQualitySeverityLabel(severity: LibraryQualityIssueSeverity): String =
        libraryQualitySeverityLabels[severity] ?: severity.name
    fun libraryQualityDecisionStateLabel(state: DesktopLibraryQualityIssueDecisionState): String =
        libraryQualityDecisionStateLabels[state] ?: state.name
    fun libraryQualityIssueGuidance(type: LibraryQualityIssueType): String? =
        when (type) {
            LibraryQualityIssueType.SPLIT_SERIES_CANDIDATE -> libraryQualitySplitSeriesGuidance
            LibraryQualityIssueType.MERGE_SERIES_CANDIDATE -> libraryQualityMergeSeriesGuidance
            else -> null
        }
    fun downloadFilterTitle(filter: DownloadQueueFilter): String = downloadFilterTitles[filter] ?: filter.label
}
